# Database patches for dev environment
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
stringData:
  POSTGRES_DB: subscriptions
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: subscriptions
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  hostPath:
    path: /tmp/postgres-data-dev