apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../base/database/database.yaml
- ../base/frontend/frontend.yaml
- ../base/product-service/product-service.yaml
- ../base/order-service/order-service.yaml

commonLabels:
  environment: staging